version: '3'

services:
  mongo:
    image: mongo
    container_name: monguito
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  db:
    image: mysql
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: angelito123
      MYSQL_DATABASE: usuarios
    volumes:
      - './mysql:/var/lib/mysql'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serverAng
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      # - mongo
      - db
    volumes:
      - './:/usr/src/dockerserver'
    command: npm run dev

volumes:
  mongodb_data:
